CasaDelight/CasaDelight/Controllers/MenuController.cs
using CasaDelight.DataAccess.Repository;
using CasaDelight.Models.Models;
using CasaDelight.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CasaDelight.Controllers
{
    public class MenuController : Controller
    {

        private readonly IWebHostEnvironment _hosting;
        private readonly IUnitofWork _unitofWork;

        public MenuController(IUnitofWork unitofWork, IWebHostEnvironment hosting)
        {
            _unitofWork = unitofWork;
            _hosting = hosting;
        }

        //main page of admin
        //Read
        [Authorize]
        public IActionResult Index()
        {
            var model = new MenuViewModel
            { 
                Dish = _unitofWork.Dishes.GetAll()
            };

            return View(model);
        }


        //Create
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(CreateViewModel createdDish)
        {
            if (ModelState.IsValid)
            {
                string fileName = PhotoProcess(createdDish);

                Dish newDish = new()
                {   
                    DishImage = fileName,
                    DishName = createdDish.DishName,
                    DishDesc = createdDish.DishDesc,
                    DishPrice = createdDish.DishPrice
                };

                _unitofWork.Dishes.Add(newDish);
                _unitofWork.Save();
                return RedirectToAction("Index");
            }

            return View();
        }


        //details
        public IActionResult Details(int id)
        {
            var dish = _unitofWork.Dishes.Get(id);

            if (dish == null)
            {
                return NotFound();
            }

            return View(dish);
        }

        //update
        public IActionResult Update(int id)
        {
            var dish = _unitofWork.Dishes.Get(id);

            if (dish == null)
            {
                return NotFound();
            }

            UpdateViewModel updateViewModel = new()
            {
                DishName = dish.DishName,
                DishDesc = dish.DishDesc,
                DishPrice = dish.DishPrice,
                ExistingImage = dish.DishImage
            };
            return View(updateViewModel);
        }

        [HttpPost]
        public IActionResult Update(UpdateViewModel editedDish)
        {
            if (ModelState.IsValid)
            {
                Dish dish = _unitofWork.Dishes.Get(editedDish.Id);
                dish.DishName = editedDish.DishName;
                dish.DishDesc = editedDish.DishDesc;
                dish.DishPrice = editedDish.DishPrice;

                if(editedDish.DishImage != null)
                {
                    if(editedDish.ExistingImage != null)
                    {
                        string filePath = Path.Combine(_hosting.WebRootPath,
                            "images", editedDish.ExistingImage);
                        System.IO.File.Delete(filePath);
                    }
                    dish.DishImage = PhotoProcess(editedDish);
                }

                _unitofWork.Dishes.Update(dish);
                _unitofWork.Save();
                return RedirectToAction("Index");
            }

            return View();
        }

        //display and saving img
        private string PhotoProcess(CreateViewModel editedDish)
        {
            string fileName = null;
            if (editedDish.DishImage != null)
            {
                string uploadPhoto = Path.Combine(_hosting.WebRootPath, "images");
                fileName = Guid.NewGuid().ToString() + "_" + editedDish.DishImage.FileName;
                string filePath = Path.Combine(uploadPhoto, fileName);
                using var fileStream = new FileStream(filePath, FileMode.Create);
                editedDish.DishImage.CopyTo(fileStream);
            }

            return fileName;
        }

        //delete
        public IActionResult Delete(int id)
        {
            var dish = _unitofWork.Dishes.Get(id);

            if (dish == null)
            {
                return NotFound();
            }
            _unitofWork.Dishes.Remove(dish);
            _unitofWork.Save();

            return RedirectToAction("Index");
        }
    }
}

CasaDelight/CasaDelight/Controllers/OrderController.cs
using CasaDelight.DataAccess.Repository;
using CasaDelight.Models.Models;
using CasaDelight.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CasaDelight.Controllers
{
    public class OrderController : Controller
    {
        private readonly IUnitofWork _unitofWork;

        List<Dish> _cartList = new List<Dish>();


        public OrderController(IUnitofWork unitofWork)
        {
            _unitofWork = unitofWork;
                       
        }


        public IActionResult Index()
        {
            var model = new OrderViewModel
            {
                Dish = _unitofWork.Dishes.GetAll()
            };

            return View(model);
        }

        public IActionResult Cart(int id)
        {
            var dish = _unitofWork.Dishes.Get(id);

            if (dish == null)
            {
                return NotFound();
            }

            _cartList.Add(dish);

            return View(_cartList);
        }

        //placeorder
        public IActionResult PlaceOrder()
        {
            return View();
        }

        [HttpPost]
        public IActionResult PlaceOrder(Order order)
        {
            Order newOrder = new Order
            {
                PhoneNumber = order.PhoneNumber
            };

            _unitofWork.Orders.Add(newOrder);
            _unitofWork.Save();

            return View();
        }


    }
}

CasaDelight/CasaDelight/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CasaDelight</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Casa Delight</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Make Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Contact</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CasaDelight - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CasaDelight/CasaDelight/Views/Shared/_Login.cshtml
@using CasaDelight.Models.Models

@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> signInManager

@if (signInManager.IsSignedIn(User))
{
    <form method="post" id="logoutForm" asp-action="LogOff" asp-controller="Account">
        <ul class="nav navbar-nav">
            <li class="text-dark nav-link">Hello, @User.Identity.Name! </li>
            <li><a class=" nav-link  text-dark" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav">
        <li class="nav-item">
            @*@Html.ActionLink("Sign Up", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })*@
            <a class="nav-link  text-dark" id="registerLink" asp-controller="Account" asp-action="Register">Register</a>
        </li>
        <li>
            @*@Html.ActionLink("Sign In", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })*@
            <a class="nav-link  text-dark" id="loginLink" asp-controller="Account" asp-action="Login">Sign In</a>
        </li>
    </ul>
}